### ISSUE TITLE
Incorrect version message for iotivity-node on Ostro image

### ISSUE THREAD

**Issue by wanghongjuan** [ostroproject/ostro-os#108]
From the latest Ostro image#452(https://download.ostroproject.org/builds/ostro-os/2016-05-19_05-41-13-build-452) get the latest release version of iotivity-node is `1.1.0-2` and show the version is `1.0-r0` in  https://download.ostroproject.org/builds/ostro-os/2016-05-19_05-41-13-build-452/sources/x86_64-ostro-linux/iotivity-node-1.0-r0/. The version is `1.1.0-2` in `iotivity-node-1.0-r0.tar.gz `. The the commit id is same as repository iotivity-node in this repository(https://github.com/ostroproject/ostro-os/blob/master/meta-iot-web/recipes-web/iotivity-node/iotivity-node.bb).

**Comment by pohly** [comment]
@nagineni looks like you need to set PV in iotivity-node.bb after updating to the more recent source code.

**Comment by nagineni** [comment]
Sorry, this dropped from my radar. I'll take a look.
