### ISSUE TITLE
Edison serial port console becomes unresponsive when connected to Linux

### ISSUE THREAD

**Issue by js333031** [ostroproject/ostro-os#112]
I downloaded and flashed pre-compiled Ostro project image onto Edison. When connected to Edison from Ubuntu, over the serial port, the terminal app becomes unresponsive. I need to disconnect and reconnect to gain access to serial console.

dmesg shows lot of these messages:
[  178.915625] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  178.916999] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  178.919856] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  179.043142] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  179.044506] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  179.047299] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  179.203959] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA

I have tried SecureCRT, minicom and screen. 115200, 8N1, no flow-control.

**Comment by js333031** [comment]
If I use Windows host + Tera Term, I don't see the dmesg logs (HSU serial...). The serial console is also stable w/Windows.

**Comment by gvancuts** [comment]
The last time I tried, this was from a Fedora host (and I never saw these). Can you clarify which Ostro image you used so I can give this another go.

**Comment by js333031** [comment]
I used [this](https://download.ostroproject.org/releases/ostro-os/milestone/2016-05-02_00-09-47-build-440/) as well as images I'm compiling locally.

**Comment by gvancuts** [comment]
@uhofemei , would you be able to test this?

**Comment by uhofemei** [comment]
@js333031 are you using the same micro USB cable when connecting to the Edison from a Windows host?

**Comment by js333031** [comment]
yes

**Comment by uhofemei** [comment]
I have not seen this issue and am out of ideas how to fix this. Sorry.

**Comment by js333031** [comment]
In the dmesg output below, I used my dual-boot system. First, booted into Ubuntu and connected to Edison via /dev/ttyUSB0. Then, after seeing the issue, rebooted into Windows 7. This is at timestamp 526, you can see when Windows+Edison recognized each other. The "HSU..DMA" issue isn't seen thereafter in Edison's dmesg.

[  516.371766] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  516.372308] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  516.373555] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  516.871199] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  516.871720] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  516.873385] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  516.874216] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  516.875043] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  516.876703] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  516.877948] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  516.879196] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  516.880026] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  516.881269] HSU serial 0000:00:04.3: Got LSR irq(0xf8) while using DMA
[  526.734646] dwc3-device dwc3-device.1: device suspended; notify OTG
[  531.486769] g_multi gadget: high-speed config #2: Multifunction with CDC ECM
[  565.978870] dwc3-device dwc3-device.1: device suspended; notify OTG
[  568.309074] g_multi gadget: high-speed config #2: Multifunction with CDC ECM
root@edison:~#

**Comment by mythi** [comment]
@js333031 Do you still see this? Have you checked your Ubuntu setup has the necessary g_* modules loaded?

**Comment by mythi** [comment]
It's expected this is host PC specific. (the Edison device operates OK without reboots when changing to win)
