### ISSUE TITLE
Unable to generate dsk.xz file

### ISSUE THREAD

**Issue by js333031** [ostroproject/ostro-os#113]
I used [these instructions](https://ostroproject.org/documentation/howtos/building-images.html#building-images) to try to bitbake my own image with the goal of using bmaptool to flash my Edison.

I modified my conf/local.conf:
MACHINE ?= "edison"
OSTRO_VM_IMAGE_TYPES = "dsk.xz"

Bitbaked:
bitbake -k ostro-image-noswupd

Images show up in tmp-glibc/deploy/images/edison/ but no file with *dsk* in its filename.

I tried to also use bmaptool on my Ubuntu dev machine, using these [these instructions](https://ostroproject.org/documentation/howtos/booting-and-installation.html) but got following error:
bmaptool: ERROR: bmap file not found, please, use --nobmap option to flash without bmap

Above error is shown when using:
sudo -E ./bmaptool copy ../images/edison/ostro-image-noswupd-edison.tar.bz2 /dev/sde

**Comment by kad** [comment]
Unfortunately flashing for platforms like Edison is not possible with bmaptool.
Edison uses different image formats and flashing mechanisms than dsk image type.

**Comment by js333031** [comment]
Thanks for the quick response. 

This needs to be properly documented.

**Comment by dbkinder** [comment]
So are certain combinations of MACHINE and OSTRO_VM_IMAGE_TYPES are not allowed then?  And no error message is shown in disallowed cases?  Indeed we should document this and update the local.conf.sample too.

The .dsk (and friends) image type only works for intel-corei7-64 and intel-quark MACHINE.
What are the available options for Edison and BeagleBone?

**Comment by kad** [comment]
Both Edison and BeagleBone has their own image type set by corresponding BSP and don't respect OSTRO_VM_IMAGE_TYPES variables.

**Comment by dbkinder** [comment]
OK.  I'm updated the building-images.rst file now...

**Comment by dbkinder** [comment]
Doc updated in PR #194 (now merged)
https://stg.ostroproject.org/documentation/howtos/booting-and-installation.html
