### ISSUE TITLE
Observation: Using USB 3.0 hub connected to Edison takes long time to flash image

### ISSUE THREAD

**Issue by js333031** [ostroproject/ostro-os#114]
I have USB 3.0 hub from [Sabrent](http://www.amazon.com/Sabrent-Charging-Ports-Adapter-HB-U930/dp/B00SIQIV04?ie=UTF8&psc=1&redirect=true&ref_=oh_aui_detailpage_o02_s02) connected to USB 3.0 port of my Ubuntu 12.04 LTS development system. No other devices are connected to this hub.

After bitbaking, I see flashall image in deploy/images/edison directory. I extracted the contents of flashall and tried to update my Edison using flashall.sh.

After about an hour, I killed the update process and retried. Once again, update was really slow. So I killed this update and moved the Edison to USB 2.0 ports directly exposed by the motherboard of dev system. This time, flashall.sh is more reasonable in updating the Edison. Update using USB 2.0 finished reasonably quickly ... < 10 mins. I never let USB 3.0 update finish.

Just an observation, maybe someone can chime in on their experience.

**Comment by gvancuts** [comment]
Hi @js333031 , a couple of quick questions:
- Have you tried the USB 3.0 without the hub?
- Have you tried different ports on the hub?
   Apparently, they are not all equal: https://www.amazon.com/review/R2PLUIAT25RN3M/ref=cm_cr_dp_title?ie=UTF8&ASIN=B00SIQIV04&channel=detail-glance&nodeID=541966&store=pc

Thanks,
Geoffroy

**Comment by js333031** [comment]
I used other ports on the hub with same slow results. Maybe I have a bad hub although I used it with an external USB HD w/o issues.

**Comment by uhofemei** [comment]
I suspect this might be in issue in negotiating a proper bus speed for USB3 in the Linux kernel for Edison. The Linux kernel for Edison is maintained by @sakoman. Steve, any ideas here? Thanks.

**Comment by sakoman** [comment]
No ideas on what is wrong.  I use a generic USB3 hub when flashing Edison and have had no speed issues.  Try another brand of hub perhaps?

**Comment by mythi** [comment]
closing. Bad USB hub causing this.
