### ISSUE TITLE
bitbake ostro-image-swupd-pre_installed_content fails

### ISSUE THREAD

**Issue by js333031** [ostroproject/ostro-os#117]
/media/development/edison/ostro/ostro-os/build$  bitbake ostro-image-swupd-pre_installed_content
Loading cache: 100% |###########################################################################################################################################################################################################################################| ETA:  00:00:00
Loaded 2738 entries from dependency cache.
ERROR: Nothing PROVIDES 'ostro-image-swupd-pre_installed_content'. Close matches:
  ostro-image-swupd-all

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

/media/development/edison/ostro/ostro-os/build$

**Comment by js333031** [comment]
I think what I reported is incorrect. I think if Step 2 of https://ostroproject.org/documentation/howtos/software-update-server.html was performed, I wouldn't have encountered the bitbake error.

**Comment by gvancuts** [comment]
Hi @js333031 , are you saying you are now past this error?

**Comment by mythi** [comment]
Closing as it looks there's no error.
