### ISSUE TITLE
Using swupd to list packages core-dumps

### ISSUE THREAD

**Issue by js333031** [ostroproject/ostro-os#118]
root@edison:~# swupd bundle-add -u http://192.168.2.122:8000 --list -V
swupd-client bundle adder 2.87
   Copyright (C) 2012-2015 Intel Corporation
   bsdiff portions Copyright Colin Percival, see COPYING file for details

Aborted (core dumped)
root@edison:~# 

It's not clear on ostro or CL websites how one uses swupd utility other than which directory needs to be exposed via a web-server. Maybe this can be added to the Ostro docs.

On my build machine, I am running `python -m SimpleHTTPServer 8000` in build/tmp-glibc/deploy/swupd/edison/ostro-image-swupd/www directory.

Then, using desktop browser, I am able to browse to http://<server IP>:8000. For example, I can retrieve http://<server IP>:8000/version/format3/latest.

Once having verified the web-server is working, verify Edison can use the SW update server:
root@edison:~# swupd update -u http://192.168.2.122:8000 
swupd-client software update 2.87
   Copyright (C) 2012-2015 Intel Corporation
   bsdiff portions Copyright Colin Percival, see COPYING file for details

Update started.
Querying server version.
Version on server (53123290) is not newer than system version (53123290)
Update exiting.
root@edison:~#

**Comment by gvancuts** [comment]
I fully agree... we need to add more to our documentation. The fact that it core dumps could be considered a bug in itself but ultimately, we need to document more clearly that there is no URL predefined in the system for swupd to operate. We should also describe how to configure such URL (both at bitbake time, via local.conf or elsewhere and in a running image).

@uhofemei @dbkinder , can you add this to our doc requirements?

**Comment by dbkinder** [comment]
The last mailing list message I’ve seen about this said:

- define your SWUPD_URL (to be done, not currently supported)

How does one configure the URL?

-- david

**Comment by dbkinder** [comment]
BTW,  https://github.com/ostroproject/ostro-os/issues/30#issuecomment-204940817  was the same issue (and was closed).
-- david


From: Kinder, David B
Sent: Thursday, June 02, 2016 9:09 AM
To: 'ostroproject/ostro-os' <reply@reply.github.com>; ostroproject/ostro-os <ostro-os@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [ostroproject/ostro-os] Using swupd to list packages core-dumps (#118)

The last mailing list message I’ve seen about this said:

- define your SWUPD_URL (to be done, not currently supported)

How does one configure the URL?

-- david

**Comment by pohly** [comment]
Currently the URL always has to be given on the command line.

**Comment by gvancuts** [comment]
Thanks @pohly, is the only option or is there any conf file on a running system one can manually edit to set it?

**Comment by pohly** [comment]
The command line is the only option with the version of swupd we have right now. Changes are coming, but not in Ostro yet.

**Comment by mythi** [comment]
we now have the default ostro urls and swupd-client updated to 3.x. Closing.
