### ISSUE TITLE
Fail install python dependencies while setting up SmartHome demo

### ISSUE THREAD

**Issue by haoxli** [ostroproject/ostro-os#126]
Hi
I’m setting up SmartHome Demo[1]  in Ostro[2], but there are two dependencies fail to install.
- [Icarus](https://github.com/tripzero/icarus) [pip install error]: libraries lapack not found in ['/usr/lib']
- [Twisted](https://twistedmatrix.com/) [pip install error]: /usr/lib/gcc/x86_64-ostro-linux/5.3.0/../../../../x86_64-ostro-linux/bin/ld: cannot find –lssp

Errors looks like the libssp.so which is part of gcc runtime is missing on the image. 

I make a workaround to build Twisted in Ubuntu, and then copy python packages to Ostro, it also work.
But for Icarus, there are more dependence libs, it does not work after copy them simply. 
 
So I still hope to get the way to install them directly in Ostro.
 
Thanks in advance.
 
[1] https://github.com/01org/SmartHome-Demo 
[2] https://download.ostroproject.org/builds/ostro-os/2016-05-31_12-21-10-build-459/images/intel-corei7-64/ostro-image-swupd-dev-intel-corei7-64.dsk.zip

**Comment by gvancuts** [comment]
Hi @haoxli , can you report this issue on the SmartHome-Demo repo directly (here: https://github.com/01org/SmartHome-Demo/issues)?

I don't think we have ever tried on the latest master branch of Ostro so perhaps this is a new issue. Have you tried using Ostro 1.0?

@uhofemei , @kiendinh , can you take a look at this?

**Comment by gvancuts** [comment]
Actually, I believe @nagineni has hit this recently too.

**Comment by haoxli** [comment]
@gvancuts The image we used is Ostro 1.0, and I also report in SmartHome demo repo: https://github.com/01org/SmartHome-Demo/issues/18, thank you.
