### ISSUE TITLE
No libspp in Ostro image

### ISSUE THREAD

**Issue by uhofemei** [ostroproject/ostro-os#127]
Hi
I’m setting up SmartHome Demo[1] in Ostro[2], but there are two dependencies fail to install.

Icarus [pip install error]: libraries lapack not found in ['/usr/lib']
Twisted [pip install error]: /usr/lib/gcc/x86_64-ostro-linux/5.3.0/../../../../x86_64-ostro-linux/bin/ld: cannot find –lssp
Errors looks like the libssp.so which is part of gcc runtime is missing on the image.

I make a workaround to build Twisted in Ubuntu, and then copy python packages to Ostro, it also work.
But for Icarus, there are more dependence libs, it does not work after copy them simply.

So I still hope to get the way to install them directly in Ostro. Can we resolve this dependence issue?

Thanks in advance.

[1] https://github.com/01org/SmartHome-Demo 
[2] https://download.ostroproject.org/builds/ostro-os/2016-05-31_12-21-10-build-459/images/intel-corei7-64/ostro-image-swupd-dev-intel-corei7-64.dsk.zip

**Comment by pohly** [comment]
Also filed as https://ostroproject.org/jira/browse/OP-82

**Comment by pohly** [comment]
It looks like nothing in the image needs libssp.so.0 and the corresponding package group, packagegroup-core-buildessential, also has no explicit dependency on libssp-dev.

We can fix this issue by explicitly adding this library, but I wonder whether we also miss other libraries. Which ones do we add and which ones not? Case-by-case?

**Comment by pohly** [comment]
OTOH, my ostro-image-minimal testbuild included libssp.so. To be checked...

**Comment by pohly** [comment]
My ostro-image-minimal had been built with OE-core master, where libssp gets pulled in because something uses it. We still need a something a bit more explicit.

@uhofemei the subject of this issue mentions only libssp, but the text then also talks about lapack missing and "install them directly in Ostro". Can you clarify whether the feature request is for libssp or libssp+lapack?

**Comment by pohly** [comment]
Furthermore, we also don't seem to have the "pip" command in our ostro-image-swupd-dev. Does that also need to be added? Where did it come from when initially trying to install the SmartHome Demo?

**Comment by gvancuts** [comment]
@pohly , that seems a little counter-intuitive to have ostro-image-minimal that contains libssp but the other variants (allegedly more complete) do not. Do you know what could be causing this?

Regarding libssp and lapack, both are needed. I don't know if lapack could be a case of it being installed but not found. If it's not there, we should look to add it.

**Comment by pohly** [comment]
@gvancuts I was switching between repo branches (basically multitasking...) and built ostro-image-minimal using more recent recipes. That explains the difference.

So basically this feature request becomes "provide everything that is needed to build SmartHome Demo on Ostro OS directly in the images". I'm not sure who will have time for that and when.

**Comment by gvancuts** [comment]
Thanks for the explanation @pohly . It sounds like this lack of libssp will automatically get resolved later then?

I understand your concern on working through adding items to Ostro. Some of these tools I suspect would benefit more people than just the ones focused on re-creating the SmartHome IoT demo (e.g. pip would be quite useful for people playing with Ostro).

Are you willing to accept patches to include these libraries?

**Comment by pohly** [comment]
@gvancuts patches would indeed be very welcome.

While looking at it, I wasn't sure where to add the necessary dependencies, though. FEATURE_PACKAGES_python-runtime for pip? FEATURE_PACKAGES_tools-develop for libssp and lapack? The later does not sound quite right. Not everyone who needs the tools needs these libraries. A new "dev-libs" image feature with a corresponding packagegroup-dev-libraries that RDEPENDS on libssp-dev and lapack-dev?

**Comment by mythi** [comment]
libssp0 can now be found in the ostro-image-swupd-dev images. Checked with the latest (494) ostro-os master build
