### ISSUE TITLE
The problem of ova file with virtualbox 5.0.20

### ISSUE THREAD

**Issue by Mac-Lu** [ostroproject/ostro-os#130]
Hi Ostro-dev,

I am following the steps of Running Ostro OS in a VirtualBox* VM to use Ostro ova file with Virtualbox 5.0.20.
But it seems boot fail with the message attached. 
So, I can not use Ostro with Virtualbox.

I use the ova files as below.
ostro-image-swupd-all-intel-corei7-64-2016-06-10_14-26-11-build-463.dsk.ova
ostro-image-swupd-dev-intel-corei7-64-2016-06-10_14-26-11-build-463.dsk.ova

May I have your support of this problem?

Thanks,

![p_20160622_143240](https://cloud.githubusercontent.com/assets/17820037/16256758/dae398ca-3886-11e6-8ca4-00bf60334bb1.jpg)

**Comment by gvancuts** [comment]
Hi!

I will try that particular build later today but in the meantime here are a few things you can check:
- Can you try to hit enter in the window (just in case the system actually is up and running but just not displaying the prompt)?
- Do you have hardware acceleration turned on for virtualization?
- What is your host OS (and machine spec)?

Thanks,
Geoffroy

**Comment by Mac-Lu** [comment]
Hi gvancuts,

Thank you for your prompt reply.

Please see the infomation below.
- Can you try to hit enter in the window (just in case the system actually is up and running but just not displaying the prompt)? 
Ans: No response.
- Do you have hardware acceleration turned on for virtualization?
Ans: Do you mean VT-x ? Yes, It has.
- What is your host OS (and machine spec)?
Ans: CPU : Intel Q9400, 4G ddr2 ram, Windows 7 enterprise SP1 64bit.

I also try the 2016-06-07 ova file ostro-image-swupd-dev-intel-corei7-64.dsk.ova, same problem, too.

Thanks,
Mac

**Comment by gvancuts** [comment]
I'm downloading the image to test it here. The CPU is somewhat hold, do you have the ability to try the same thing on a more recent machine too?

I have a somewhat old Core™ i7-720QM here (but running Linux) and I have not had problems running OVA so far (but still need to try with the same image as you)

**Comment by gvancuts** [comment]
Hi @Mac-Lu , I have now tested the very same image (ostro-image-swupd-dev-intel-corei7-64-2016-06-10_14-26-11-build-463.dsk.ova) on a Windows 8.1 machine running VirtualBox 5.0.20. I did not have any problem running it. There is a newer version of VirtualBox available (5.0.22), can you try this? And also let me know if you had a chance to test on a different, more recent HW machine.

Thanks

**Comment by Mac-Lu** [comment]
Hi gvancuts,

I use the core i5 cpu to try the same test.
The ostro can be run into root command line.

Thanks for your help.
Mac

**Comment by gvancuts** [comment]
Thanks for confirming this!
