### ISSUE TITLE
can't compile openjdk-8 in local build

### ISSUE THREAD

**Issue by ereshetova** [ostroproject/ostro-os#149]
MACHINE ?= "intel-quark"
target: ostro-image-swupd
latest master
....
| --> /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/java/nio/channels/IllegalChannelGroupException.java
| --> /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/java/nio/channels/AlreadyBoundException.java
| Exception in thread "main" java.lang.InternalError: No RenderingEngine module found
| 	at sun.java2d.pipe.RenderingEngine.getInstance(RenderingEngine.java:151)
| 	at sun.java2d.pipe.LoopPipe.<clinit>(LoopPipe.java:55)
| 	at sun.java2d.SurfaceData.<clinit>(SurfaceData.java:448)
| 	at sun.java2d.SunGraphicsEnvironment.createGraphics(SunGraphicsEnvironment.java:185)
| 	at sun.java2d.HeadlessGraphicsEnvironment.createGraphics(HeadlessGraphicsEnvironment.java:89)
| 	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1182)
| 	at java.awt.image.BufferedImage.getGraphics(BufferedImage.java:1170)
| 	at build.tools.icondata.awt.ToBin.main(ToBin.java:41)
| --> /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/java/nio/channels/AcceptPendingException.java
| gensrc/GensrcIcons.gmk:106: recipe for target '/ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/sun/awt//AWTIcon64_java_icon16_png.java' failed
| make[2]: *** [/ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/sun/awt//AWTIcon64_java_icon16_png.java] Error 1
| make[2]: *** Waiting for unfinished jobs....
| --> /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/java/nio/channels/ReadPendingException.java
| Exception in thread "main" java.lang.InternalError: No RenderingEngine module found
| 	at sun.java2d.pipe.RenderingEngine.getInstance(RenderingEngine.java:151)
| 	at sun.java2d.pipe.LoopPipe.<clinit>(LoopPipe.java:55)
| 	at sun.java2d.SurfaceData.<clinit>(SurfaceData.java:448)
| 	at sun.java2d.SunGraphicsEnvironment.createGraphics(SunGraphicsEnvironment.java:185)
| 	at sun.java2d.HeadlessGraphicsEnvironment.createGraphics(HeadlessGraphicsEnvironment.java:89)
| 	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1182)
| 	at java.awt.image.BufferedImage.getGraphics(BufferedImage.java:1170)
| 	at build.tools.icondata.awt.ToBin.main(ToBin.java:41)
| --> /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/java/nio/channels/WritePendingException.java
| make[2]: *** [/ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/sun/awt//AWTIcon32_java_icon16_png.java] Error 1
| gensrc/GensrcIcons.gmk:106: recipe for target '/ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/sun/awt//AWTIcon32_java_icon16_png.java' failed
| --> /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/java/nio/channels/ShutdownChannelGroupException.java
| gensrc/GensrcExceptions.gmk:49: Building /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/java/nio/_the.channels  (from /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/jdk8u-e8bed1496ff2/jdk/src/share/classes/java/nio/channels/exceptions) (/ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/jdk8u-e8bed1496ff2/jdk/src/share/classes/java/nio/channels/exceptions /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/jdk8u-e8bed1496ff2/jdk/make/scripts/genExceptions.sh /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/java/nio/_the.exceptions.dir /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/btclasses/_the.BUILD_TOOLS_batch /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/btclasses/build/tools/generatenimbus/resources/StateImpl.template /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/btclasses/build/tools/generatenimbus/resources/Defaults.template /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/btclasses/build/tools/generatenimbus/resources/PainterImpl.template /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/btclasses/build/tools/deps/refs.allowed  newer)
| + /usr/bin/touch /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/java/nio/_the.channels
| Exception in thread "main" java.lang.InternalError: No RenderingEngine module found
| 	at sun.java2d.pipe.RenderingEngine.getInstance(RenderingEngine.java:151)
| 	at sun.java2d.pipe.LoopPipe.<clinit>(LoopPipe.java:55)
| 	at sun.java2d.SurfaceData.<clinit>(SurfaceData.java:448)
| 	at sun.java2d.SunGraphicsEnvironment.createGraphics(SunGraphicsEnvironment.java:185)
| 	at sun.java2d.HeadlessGraphicsEnvironment.createGraphics(HeadlessGraphicsEnvironment.java:89)
| 	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1182)
| 	at java.awt.image.BufferedImage.getGraphics(BufferedImage.java:1170)
| 	at build.tools.icondata.awt.ToBin.main(ToBin.java:41)
| make[2]: *** [/ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/sun/awt//AWTIcon32_java_icon24_png.java] Error 1
| gensrc/GensrcIcons.gmk:106: recipe for target '/ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/build/jdk/gensrc/sun/awt//AWTIcon32_java_icon24_png.java' failed
| BuildJdk.gmk:55: recipe for target 'gensrc-only' failed
| make[1]: *** [gensrc-only] Error 2
| /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/jdk8u-e8bed1496ff2//make/Main.gmk:115: recipe for target 'jdk-only' failed
| make: *** [jdk-only] Error 2
| ERROR: oe_runmake failed
| ERROR: Function failed: do_compile (log file is located at /ostro/ostro-os/build/tmp-glibc/work/i586-nlp-32-ostro-linux/openjdk-8/72b05-r0/temp/log.do_compile.10640)
ERROR: Task 2787 (/ostro/ostro-os/meta-java/recipes-core/openjdk/openjdk-8_72b05.bb, do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4560 tasks of which 4159 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /ostro/ostro-os/meta-java/recipes-core/openjdk/openjdk-8_72b05.bb, do_compile
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**Comment by Valtis** [comment]
What distro do you use? Openjdk compiled fine for me on Ubuntu 16.04.

**Comment by mythi** [comment]
@ereshetova Do you see this error still?

**Comment by ereshetova** [comment]
@mythi, I haven't done local build in ages, let me try to pull in updates and check

**Comment by ereshetova** [comment]
@mythi, local build took ages, but completed successfully. so this issue can be closed.

**Comment by mythi** [comment]
@ereshetova thanks for taking the time to check it!
