### ISSUE TITLE
Upgrade required for gstreamer-vaapi to >= 1.8.2

### ISSUE THREAD

**Issue by laxigithub** [ostroproject/ostro-os#163]
The current version of gstreamer-vaapi-0.7.0 is old in Ostro and it should be > = 1.8.2.
With the older version in Ostro, we get garbled results in the playback and some of the codecs are also not supported. 
Details: 
Current version of gstreamer-vaapi-0.7.0 doesn’t support HEVC and VP9 encode. 
gstreamer-vaapi-1.8.2 supports HEVC encode and doesn’t support VP9 encode. 
gstreamer-vaapi-1.9.1 supports both HEVC and VP9 encode. 
This might require other Gstreamer plugins like Bad also to be updated to 1.9.1

**Comment by mythi** [comment]
ostro-os now provides this.

**Comment by laxigithub** [comment]
Hi Mikko,
Ostro build #182 still has gstreamer-vaapi-1.0_0.7.0.bb, can you please merge this PR into latest Ostro builds ?

Thanks,
Laxman
