### ISSUE TITLE
Can't load .ova pre-built image in VirtualBox

### ISSUE THREAD

**Issue by KDuzinkiewicz** [ostroproject/ostro-os#166]
Hi, 
   I'm trying to use a pre-built Ostro OS image (ostro-image-swupd-dev-intel-corei7-64-2016-07-24_00-09-20-build-485.dsk.ova) with VirtualBox 5.0.20 according to the documentation but all I get is the following message:

![image](https://cloud.githubusercontent.com/assets/19652894/17936679/de4437a2-6a1f-11e6-8ed7-9f2f4dbdf02f.png)

I'm a little bit confused since I don't have any .vmdk file - I was thinking that .ova file is the only one needed. 

Any help would be appreciated. 

Regards, 

Karol

**Comment by gvancuts** [comment]
The vmdk file is part of the OVA file. Could it be that the file you have downloaded got truncated or corrupted? We don't publish checksums for the files but please check that the size is correct and perhaps try to download it again?

I will try with that build on my side too and will let you know.

Thanks

**Comment by gvancuts** [comment]
I was able to import the same build into VirtualBox (Version 5.0.22 r108108) on Windows.

The md5 checksum of the file I used is: c388d0f7df3cd4ef672fab9a672ddcfa

**Comment by KDuzinkiewicz** [comment]
Ok, thanks for clarification. I'll give it another try on my side (re-download) and check again. 
Thanks for your prompt answer.
