### ISSUE TITLE
I need some guideline regarding custom bsp meta layer creation for mips

### ISSUE THREAD

**Issue by anindya1989** [ostroproject/ostro-os#169]
I need some guideline regarding some custom bsp meta layer creation for mips. I tried with yocto-bsp create {MACHINE_NAME} {ARCH} but it is saying that yocto-bsp command not found. So, please give some input related to that.

**Comment by mythi** [comment]
Please refer to Yocto Project BSP Guide: http://www.yoctoproject.org/docs/2.1/bsp-guide/bsp-guide.html
