### ISSUE TITLE
Ostro image can not automatically boot up and auto-login as root on Edison

### ISSUE THREAD

**Issue by wanghongjuan** [ostroproject/ostro-os#181]
According to this [document][]: `Once flashing is done, the image will automatically boot up and auto-login as root, no password is required`. Actually, the image can not automatically boot up. 
I find a [guide][], following this guide, the image can boot up and auto-login as `root`.
Is there anything wrong when flash the image? Or lack of some steps when boot up the image?

[document]: https://ostroproject.org/documentation/howtos/booting-and-installation.html#intel-edison
[guide]: https://software.intel.com/en-us/setting-up-serial-terminal-on-system-with-linux

**Comment by gvancuts** [comment]
I'm not entirely following you. Are you saying that you never get a prompt on the serial line after flashing Ostro on your Edison board but you do when using a different (non-Ostro) image?

If so, can you tell us a bit more about how the flashing process went? Did you see any time-out, error, etc.?

**Comment by wanghongjuan** [comment]
I had some misunderstanding, I could see the system boot up automatically in the serial console by `screen` command. So close this.
