### ISSUE TITLE
No Ostro build#512 images found for intel-quark arch at download.ostroproject.org

### ISSUE THREAD

**Issue by qiuzhong** [ostroproject/ostro-os#211]
[Ostro images build#512 for intel-quark](https://download.ostroproject.org/builds/ostro-os/2016-12-03_04-11-18-build-512/images/intel-quark/) are missing at [download.ostroproject.org](https://download.ostroproject.org/builds/ostro-os/2016-12-03_04-11-18-build-512/images/intel-quark/). However, the [build log](https://download.ostroproject.org/builds/ostro-os/2016-12-03_04-11-18-build-512/bitbake-intel-quark-2016-12-03_04-11-18-build-512.log) shows there're no fatal errors during the build procedure. [Normally](https://download.ostroproject.org/builds/ostro-os/2016-11-21_07-41-18-build-511/images/intel-quark/), there should be 8 dsk.xz files for intel-quark arch.

Only the images for intel-quark are missing. Images for other arches (edison, intel-corei7-64) can be found.

**Comment by okartau** [comment]
worker node went offline during job. I restarted job now, sync is going

**Comment by qiuzhong** [comment]
The Ostro images build#512 for intel-quark can be found now. So close this issue.
