### ISSUE TITLE
Error when running simpleclient - GET Response error: 29

### ISSUE THREAD

**Issue by nataliath** [ostroproject/ostro-os#220]
When I run simpleclient in <iotivity>/out/linux/x86_64/release/resource/examples I have this output:

```
Found another resource, ignoring
onGET Response error: 29
```

Anyone know about the error?

**Comment by gvancuts** [comment]
Hi @nataliath , can you tell us a bit more about your environment? What is the OS version you're running on and other relevant info?

**Comment by nataliath** [comment]
Thank you for your reply.
Yes I am following these instructions:
https://www.iotivity.org/documentation/linux/getting-started

(I downloaded the iotivity source code and didn't followed the five steps)

When I execute the 
`$ ./simpleclient`
command in the terminal it returns this error and can't execute GET, PUT.

Simpleserver is in another terminal.

**Comment by gvancuts** [comment]
Hi @nataliath , I saw you posted the same question to the iotivity-dev mailing list. That is the right course of action and the IoTivity community is the right one for answering your question (especially since you do not seem to use Ostro). Can you close this issue?

**Comment by nataliath** [comment]
@gvancuts Thank you!!
