### ISSUE TITLE
Error with swupd (core dumped)

### ISSUE THREAD

**Issue by thiagogcm** [ostroproject/ostro-os#30]
Hi. Just got the Ostro latest build (414) running on a Galileo Gen 2 and this happened when I tried the swupd tool:

root@intel-quark:~# swupd verify
swupd-client software verify 2.87
   Copyright (C) 2012-2015 Intel Corporation
   bsdiff portions Copyright Colin Percival, see COPYING file for details

Verifying version 4140
Unable to download 4140 Manifest.MoM
Inspected 0 files
  0 files did not match
Verify successful

================================

root@intel-quark:~# swupd update
swupd-client software update 2.87
   Copyright (C) 2012-2015 Intel Corporation
   bsdiff portions Copyright Colin Percival, see COPYING file for details

Update started.
Querying server version.
Preparing to update from 4140 to 7160
Querying current manifest.
Failure retrieving manifest from server
Update exiting.

=================================
root@intel-quark:~# swupd bundle-add --list
swupd-client bundle adder 2.87
   Copyright (C) 2012-2015 Intel Corporation
   bsdiff portions Copyright Colin Percival, see COPYING file for details

Aborted (core dumped)

**Comment by pohly** [comment]
I'm not sure what build 414 is. Where did you get it from?

But regardless of that, the problem most likely is (in all cases) that there is no default URL configured for the update stream. I don't think we have published swupd update streams for any of the official images.

I'm currently working on integration meta-swupd into our builds (see 
https://github.com/ostroproject/ostro-os/pull/25) and we will have swupd update streams once that's done.

**Comment by kad** [comment]
@pohly build 414 is current build of master branch: https://download.ostroproject.org/builds/ostro-os/

**Comment by mythi** [comment]
The core dump issue should be fixed (to not core dump if something is not right) and reported in https://github.com/clearlinux/swupd-client/issues

in 414 swupd is not expected to work so we can close this issue.

**Comment by thiagogcm** [comment]
Ok. 

@pohly  Taking a look at your PR, shouldn't you include nodejs-runtime-tools as per discussed in PR #78 ?

**Comment by pohly** [comment]
On Mon, 2016-04-04 at 14:49 -0700, Thiago Moura wrote:
> Ok. 
> 
> @pohly Taking a look at your PR, shouldn't you include
> nodejs-runtime-tools as per discussed in PR #78 ?

That patch is not yet in ostro-os master, which is what my PR is based
on. I'll include it once @mythi updates ostro-os master and I rebase my
PR.
