### ISSUE TITLE
remove klogd and syslogd from our images

### ISSUE THREAD

**Issue by barbieri** [ostroproject/ostro-os#31]
Ostro already uses systemd-journald, then there is no need to ship klogd and syslogd in our images. These are being added on purpose with busybox-XXX.services in our recipes.

@mythi or @pohly can you take a look? or point someone to look at it?

**Comment by mythi** [comment]
@barbieri these seem to be part of default busybox config. I'll check if it's easy to drop them.

**Comment by pohly** [comment]
On Wed, 2016-04-06 at 07:43 -0700, Mikko Ylinen wrote:
> @barbieri these seem to be part of default busybox config. I'll check
> if it's easy to drop them.

If it's busybox, then we shouldn't bother and instead do it as part of
the toybox integration. Actually, toybox does not implement these
daemons, so they are probably gone already in
https://github.com/pohly/ostro-os/tree/toybox

**Comment by barbieri** [comment]
https://github.com/ostroproject/ostro-os/blob/master/meta/recipes-core/busybox/busybox.inc indeed. but it's a split package we could skip installing.

**Comment by mythi** [comment]
@pohly I agree and I was going to add a note about that.

**Comment by pohly** [comment]
Given that replacement of Busybox with Toybox might be further out than we thought, I also prepared a .bbappend for Busybox which disables the daemons. I'd prefer to do a PR yet (enough going on already).

**Comment by mythi** [comment]
On Wed, Apr 13, 2016 at 12:12 PM, Patrick Ohly <notifications@github.com>
wrote:

> Given that replacement of Busybox with Toybox might be further out than we
> thought, I also prepared a .bbappend for Busybox which disables the
> daemons. I'd prefer to do a PR yet (enough going on already).
>
>
>
I too had this done while checking what's going on :)

**Comment by mythi** [comment]
Fixed.
