### ISSUE TITLE
systemd: split legacy initd/sysv in its own package

### ISSUE THREAD

**Issue by barbieri** [ostroproject/ostro-os#33]
we should split things related to legacy initd/sysv in its own package and only pull this when needed so this shouldn't be in our reference images. That means all the inictl sockets, sysv and rc-local generators.

My team already provided a patch and it wasn't integrated then we stopped the effort, one can resume based on http://patchwork.openembedded.org/patch/88007/

**Comment by msivosuo** [comment]
@jku - ping.

**Comment by jku** [comment]
Cheers.

So the reason for separate packages (instead of just extensive PACKAGECONFIG) is that you want to ship a subset but still want to provide the other stuff as binary packages? That makes sense I suppose...

The latest patchset from Bruno is actually this one http://lists.openembedded.org/pipermail/openembedded-core/2015-May/thread.html#104869
It is quite granular... but I'll take a closer look at this after yocto 2.1 quiets down a bit for me (looks like soon).

**Comment by barbieri** [comment]
yes, that's the rationale. If you use PACKAGECONFIG, then our sstate-mirror will be useless for people willing to tweak.

also, systemd is a single GIT repo with multiple internal projects: udev, timedated, localed... they all live together since they may share some helpers (like `src/shared`) and they test them together, but nothing prevents one to remove/add them individually as I'm proposing.

When I did that patch Bruno tried to upstream, I could bring systemd on par with busybox/sysvinit for baseline systems (of course I did it without busybox or shell), it went down from >30Mb to 7Mb, but that was without udev and journal and all other components, just the requirements to boot -- the same busybox/sysvinit was doing.

The nice advantage of systemd is scaling up: whenever on busybox it goes exponential as you need to bring in different projects, each with their own hacks, with systemd it's more linear as you gradually add its components. Not to say that with systemd, even in the smallest version, you have all the isolation (containers, namespaces), you have timers (with sysvinit you need cron/at) and you have socket-activation (with sysvinit you need xinetd/inetd).

You can use this as justification when trying to upstream those changes.

**Comment by mythi** [comment]
Closing as wontfix for ostro-os for now.
