### ISSUE TITLE
flashall.sh script does not work with ostro-image-dev-edison

### ISSUE THREAD

**Issue by petreeftime** [ostroproject/ostro-os#4]
The ostro-image-dev-edison image available here: https://download.ostroproject.org/releases/ostro-os/milestone/v1.0.0-pre/ contains a flashall.sh script which does not work. The reason for this is that the disk images contain the -dev- qualifier, but the script is looking for a file without it.

Error from flash.log:
```
dfu-util: Could not open file /storage/Downloads/toFlash/ostro-image-edison.hddimg for reading: No such file or directory
```
The file it should be looking for instead:
```
/storage/Downloads/toFlash/ostro-image-dev-edison.hddimg
```

**Comment by jlaako** [comment]
You can use '-i' option for the flashall.sh script to specify the root image name. For example '-i ostro-image-dev'

**Comment by daweiwu** [comment]
Yes. You need '-i' to flash dev image. I have tried the build 399, flashing with '-i ostro-image-dev' has no problem.

**Comment by pohly** [comment]
Let's consider this an enhancement: the flashall.sh script that gets published together with a certain image should have that image name as default for the -i option.

**Comment by jlaako** [comment]
@pohly at the moment, bitbake build results end up in same place under tmp/deploy/images regardless of image type. So things like bootloaders, firmwares and flashing scripts are not image specific and are not even rebuilt for different image types since they don't end up on the image itself.

**Comment by pohly** [comment]
@jlaako where is ostro-image-dev-edison-2016-03-02_09-51-12-build-399.toflash.tar.bz2 gettting created? Some code somewhere is taking flashall.sh and combining it with ostro-image-dev. That same code could change the default.

**Comment by jlaako** [comment]
@pohly If one ever uses that tarball in first place at all. If one builds image using bitbake and wants to flash it, it is extremely inconvenient to use the tarball. At least I use just the tmp/deploy/images/edison/flashall/flashall.sh straight.

**Comment by pohly** [comment]
On Tue, 2016-03-08 at 00:08 -0800, Jussi Laako wrote:
> @pohly If one ever uses that tarball in first place at all.

The original reporter did, which is not surprising because the tarballs
are all that is offered by our download pages:
https://download.ostroproject.org/releases/ostro-os/milestone/v1.0.0-pre/

Anyway, Sasha has prepared a fix for this issue:
https://github.com/ostroproject/meta-ostro-bsp/pull/4

**Comment by jlaako** [comment]
Just that the proposed "fix" is inconsistent when flashing straight from the deploy/images/edison directory which is the main developer use case anyway.
