### ISSUE TITLE
systemd: split udev in its own package

### ISSUE THREAD

**Issue by barbieri** [ostroproject/ostro-os#45]
Similar to #33, work was already done http://patchwork.openembedded.org/patch/88007/ and needs to be resumed.

udev is an important part to systems with dynamic hardware, but not all products are like that and can drop udev in favor of manual handling.

We should do this in a way udev is split but pulled in by default, so people may blacklist it to remove the daemon, services and utilities. This includes hwdb and the likes.

**Comment by mythi** [comment]
Closing as wontfix for ostro-os for now.
