### ISSUE TITLE
systemd: split journal in its own package

### ISSUE THREAD

**Issue by barbieri** [ostroproject/ostro-os#48]
Similar to #33, work was already done http://patchwork.openembedded.org/patch/88007/ and needs to be resumed.

not all products will need full logging capabilities, so no need to ship journal services, client and daemon.

This is useful for most scenarios and should be pulled in by default, but users should be able to blacklist to save some space. Systemd provides another tools that will redirect logging requests to /dev/kmsg, that should be provided to replace the journal

**Comment by mythi** [comment]
Closing as wontfix for ostro-os for now.
