### ISSUE TITLE
systemd: split systemctl and other cmdline tools in its own package

### ISSUE THREAD

**Issue by barbieri** [ostroproject/ostro-os#49]
Similar to #33, work was already done http://patchwork.openembedded.org/patch/88007/ and needs to be resumed.

Tools like systemctl, systemd-cgls and systemd-cgtop are only useful in interactive/shell environments. In real products the applications should talk to systemd directly over dbus, thus systemctl doesn't need to be provided.

We may need to adapt some code we have to make that possible, like iot-appfw

**Comment by mythi** [comment]
Closing as wontfix for ostro-os for now.
