### ISSUE TITLE
The ostroproject.org website doesn't seem to explain how to use SSTATE_MIRROR

### ISSUE THREAD

**Issue by igor-stoppa** [ostroproject/ostro-os#6]
To speed up the creation of an image, using the SSTATE_MIRROR is fundamental, however I couldn't locate instructions about it.

**Comment by kad** [comment]
@dbkinder please update doc/howtos/building-images.rst to include uncommenting SSTATE_MIRROR line.

**Comment by dbkinder** [comment]
PR submitted (https://github.com/ostroproject/meta-ostro/pull/27).  Please review.

**Comment by kad** [comment]
Closing, as ostroproject/meta-ostro/pull/27 got merged.
