### ISSUE TITLE
Missing a dependency on bmap-tools-native when building .dsk.vdi.zip images

### ISSUE THREAD

**Issue by gvancuts** [ostroproject/ostro-os#70]
Generating an Ostro image was failing with the following message below until I manually built bmap-tools-native on my dev machine. One of the customisation that I have in my conf/local.conf file is that I only build .dsk.vdi.zip images. Attempting to build a .dsk image succeeded.

~/ostro-os/build$ bitbake ostro-image-noswupd Loading cache: 100% |##################################################################################| ETA:  00:00:00 Loaded 2602 entries from dependency cache.
Parsing recipes: 100% |################################################################################| Time: 00:00:00 Parsing of 1992 .bb files complete (1991 cached, 1 parsed). 2602 targets, 1290 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.30.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "universal"
TARGET_SYS        = "x86_64-ostro-linux"
MACHINE           = "intel-corei7-64"
DISTRO            = "ostro"
DISTRO_VERSION    = "1.0~snapshot-20160422"
TUNE_FEATURES     = "m64 corei7"
TARGET_FPU        = ""
meta-ostro-fixes
meta
meta-selftest
meta-intel
meta-ostro
meta-oic
meta-security-smack
meta-security-framework
meta-integrity
meta-intel-iot-middleware
meta-ostro-bsp
meta-edison-bsp
meta-iot-web
meta-yocto-bsp
meta-iotqa
meta-appfw
meta-security-isafw
meta-swupd
meta-networking
meta-oe
meta-python
meta-java
meta-soletta      = "master:d6e864e11c561d1c51a4562bcc11ad2e9946211d"

NOTE: Preparing RunQueue
NOTE: Checking sstate mirror object availability (for 115 objects)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: ostro-image-noswupd-1.0-r0 do_image_dsk: Function failed: do_image_dsk (log file is located at /home/gvancuts/ostro-os/build/tmp-glibc/work/intel_corei7_64-ostro-linux/ostro-image-noswupd/1.0-r0/temp/log.do_image_dsk.9940)
ERROR: Logfile of failure stored in: /home/gvancuts/ostro-os/build/tmp-glibc/work/intel_corei7_64-ostro-linux/ostro-image-noswupd/1.0-r0/temp/log.do_image_dsk.9940
Log data follows:
| DEBUG: Executing python function set_image_size
| DEBUG: Python function set_image_size finished
| DEBUG: Executing shell function do_image_dsk Traceback (most recent 
| call last):
|   File "/home/gvancuts/ostro-os/meta-ostro/lib/image-dsk.py", line 16, in <module>
|     from bmaptools import Filemap
| ImportError: No module named bmaptools
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_image_dsk (log file is located at 
| /home/gvancuts/ostro-os/build/tmp-glibc/work/intel_corei7_64-ostro-lin
| ux/ostro-image-noswupd/1.0-r0/temp/log.do_image_dsk.9940)
ERROR: Task 17 (/home/gvancuts/ostro-os/meta-ostro/recipes-image/images/ostro-image-noswupd.bb, do_image_dsk) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2831 tasks of which 2830 didn't need to be rerun and 1 failed.
No currently running tasks (2589 of 2833)

Summary: 1 task failed:
  /home/gvancuts/ostro-os/meta-ostro/recipes-image/images/ostro-image-noswupd.bb, do_image_dsk
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by kad** [comment]
@gvancuts please document what you have custom in conf/local.conf, like specific image types.

**Comment by gvancuts** [comment]
Here is what I have in my local.conf.

OSTRO_VM_IMAGE_TYPES = "dsk.vdi.zip"

That's the only line I've tweaked (besides uncommenting the line with ostro-os-development.inc)

**Comment by gvancuts** [comment]
If you want to reproduce this:
- Make sure you don't have bmaptools installed on your dev machine
- ostro-os/build$ bitbake bmap-tools-native -c clean
- ostro-os/build$ bitbake ostro-image-noswupd
-> It fails as described above

To work around the problem:
- ostro-os/build$ bitbake bmap-tools-native
- ostro-os/build$ bitbake ostro-image-noswupd
-> It works

I can copy-paste my entire conf/local.conf if you want.

**Comment by kad** [comment]
It looks like if output type contains more than one chained compression method, original dependencies of image type ("dsk") are lost somehow. @rossburton, any ideas why ?

**Comment by kad** [comment]
looks like imagetypes_getdepends() is broken currently for chained types and require improvements.

**Comment by kad** [comment]
@rossburton created draft patch that would be adjusted and send to upstream to fix that issue:
http://git.yoctoproject.org/cgit.cgi/poky-contrib/commit/?h=ross/mut&id=4541f8a777fb1de147ad2aa07dd9f87b027acba9

**Comment by gvancuts** [comment]
Thanks for the update @kad

**Comment by rossburton** [comment]
Submitted to oe-core.

**Comment by kad** [comment]
fix was merged as e13563cdb134a677549db482bd1bfec4cc786af9
