### ISSUE TITLE
bitbake ostro-image-swupd-dev , the default route can't work

### ISSUE THREAD

**Issue by wenij** [ostroproject/ostro-os#86]
hi ,

Build dsk image with 'bitbake ostro-image-swupd-dev' for Quark platform.
it will create one ve-iodine-node interface with ip address 169.254.54.224, and  its routing will have issue to send out packaet.
What does this  ve-iodine-node interface used for?

===
root@intel-quark:/usr/lib# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         0.0.0.0         0.0.0.0         U     0      0        0 ve-iodine-node
0.0.0.0         0.0.0.0         0.0.0.0         U     2048   0        0 ve-iodine-node
10.0.0.0        0.0.0.0         255.255.255.252 U     0      0        0 ve-iodine-node
10.58.85.212    192.168.20.254  255.255.255.255 UGH   0      0        0 enp0s20f6
169.254.0.0     0.0.0.0         255.255.0.0     U     0      0        0 ve-iodine-node
192.168.20.0    0.0.0.0         255.255.255.0   U     0      0        0 enp0s20f6
192.168.20.254  0.0.0.0         255.255.255.255 UH    0      0        0 enp0s20f6
192.168.50.2    192.168.20.254  255.255.255.255 UGH   0      0        0 enp0s20f6
192.168.50.111  192.168.20.254  255.255.255.255 UGH   0      0        0 enp0s20f6
==

wenij

**Comment by ipuustin** [comment]
@klihub just did some work related to the routing and permission handling of the containerized apps, see https://github.com/01org/meta-intel-iot-security/pull/118. It could be that this is an instance of the same bug?

**Comment by klihub** [comment]
That's the IPv4 stateless autoconfiguration (RFC3927) address for the interface. It won't/shouldn't get routed. It is only used as a link-local address. The interface will (should) get assigned another address too, by systemd-networkd. That interface is used towards the container running one of the test/sample apps.

**Comment by mythi** [comment]
The default route works OK in the latest build.
